### PR TITLE
chore: Update @actions/core from 1.6.0 to 1.10.0

### PR DESCRIPTION
**Pull request by michaelkimball**
Had to mock `fs` more thoroughly to pass tests.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by patrick-scully-ef** [comment]
+1 to merge TY!

**Comment by devikiran-khode** [comment]
+1 to merge TY!

**Comment by shmokmt** [comment]
+1 to merge TY!

**Comment by shmokmt** [comment]
@clareliguori 
Hi, Could you review&release the PR? 👀 
We must fix deprecation warnings in a half year.

ref. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Review by iamhopaul123 — APPROVED** [review]

**Review by iamhopaul123 — APPROVED** [review]

**Pull request merged**
