### PR TITLE
feat: update to node20

### PR DESCRIPTION
**Pull request by alexndlm**
*Issue #, if available:* https://github.com/aws-actions/amazon-ecs-render-task-definition/issues/285

*Description of changes:*
- update to `node20`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by alexndlm** [comment]
@clareliguori, could you please check?

**Comment by nireld** [comment]
Please push it :)

**Comment by yamashita-takeshi** [comment]
Any updates to this?

**Comment by dannolan** [comment]
Can we please get this merged

**Comment by jlauzze** [comment]
@iamhopaul123 can you or someone who still manages this repo kindly merge this?

**Comment by jlauzze** [comment]
TY @iamhopaul123!

**Comment by patrick-scully-ef** [comment]
Release tag please and TY!

**Comment by jedipunkz** [comment]
@iamhopaul123 @alexndlm 

Please release tag. GitHub plans to transition to run on Node 20 by Spring 2024.

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Our plan is to transition all actions to run on Node 20 by Spring 2024. We will actively monitor the migration's progress and gather community feedback before finalizing the transition date.

**Pull request merged**
