### PR TITLE
feat: support dockerLabels

### PR DESCRIPTION
**Pull request by johnseekins-pathccm**
*Issue #, if available:* #272

*Description of changes:*

Add support for `dockerLabels` in task rendering. Basically updating #138 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by johnseekins-pathccm** [comment]
@sapekshm @iamhopaul123 I see you've recently worked on PRs in this repo. Any chance we could get this change merged? And maybe even a new release cut with this change?

**Review by iamhopaul123 — APPROVED** [review]

**Comment by iamhopaul123** [comment]
Hello @johnseekins-pathccm the PR looks good to me. Can you fix failed checks before merging?

**Comment by johnseekins-pathccm** [comment]
I can't run workflows, but tests are passing locally now. @iamhopaul123 , I _think_ this is ready?

**Comment by iamhopaul123** [comment]
hello @johnseekins-pathccm looks like the tests are green now. Can you follow the https://conventionalcomments.org/ and fix the title and commit?

**Comment by KollaAdithya** [comment]
@johnseekins-pathccm ! Can you change your title to `feat: support dockerLabels`

**Comment by johnseekins-pathccm** [comment]
It's pretty clear that whatever I did didn't follow semantic commits and I don't entirely understand how to fix it. Y'all are welcome to just _take_ the code in a new PR, or if someone wants to tell me _exactly_ how to format the PR to make this work, I'd love some advice.

**Comment by tristanhill-iris** [comment]
> It's pretty clear that whatever I did didn't follow semantic commits and I don't entirely understand how to fix it. Y'all are welcome to just _take_ the code in a new PR, or if someone wants to tell me _exactly_ how to format the PR to make this work, I'd love some advice.

@johnseekins-pathccm I don't think rerunning the workflow actually refreshes the values passed into it via the `context.payload.pull_request` (https://github.com/aws-actions/amazon-ecs-render-task-definition/actions/runs/6509556132/job/17971730910?pr=274#step:2:5), so it's still validating against the old PR title. You could try pushing a new commit (or amend the last one) with no changes to re-trigger the check?

**Pull request merged**
